### ISSUE TITLE
Running multiple Ice processors

### ISSUE THREAD

**Issue by ckelner** [Netflix/ice#141]
Hi,

Tried getting some attention over on the ice users group (see: https://groups.google.com/forum/#!topic/iceusers/6-BltECb9YA) -- basically want to know if there are drawbacks to running multiple processors (different machines)?

Thanks,
Chris

**Comment by vfilanovsky** [comment]
Chris, I read your post in GG, but I'm still not sure what exactly you're trying to achieve. You can run a single processor against multiple billing buckets and multiple AWS accounts. You can run multiple processors, granted you set them up to use different work buckets - in this case, you will have to run multiple readers.
You cannot run multiple processors against the same work bucket because the processors would write over each other.

**Comment by ckelner** [comment]
Hey @vfilanovsky sorry for the confusion, I'll try to clarify and simplify:

I'm running hot:hot in us-east-1 and us-west-1, 3 servers (1 in each az) per region.
I'm running both reader and processor on each server.
All servers are configured exactly the same (so they all utilize the same buckets, etc).

Is there any harm in doing it this way that you are aware of it?  Can it lead to any sort of inconsistency?  Is the only downside that one processor will overwrite another processors work in the s3 bucket (and the data transfer cost associated with that)?

Hope this is a better explanation for my question.

Thanks,
Chris

**Comment by vfilanovsky** [comment]
Yes, it can lead to inconsistency. I haven't tried running multiple processors against the same work bucket, so I cannot tell you what else can happen other than overwriting data. The configuration with multiple processors is not supported. Implement it on your own risk.

I'm still a bit fuzzy about what you're trying to achieve. Sounds like you run 6 instances of Ice against the same data. Why?

**Comment by ckelner** [comment]
High Availability, Redundancy, and latency mostly.   Not attempting to achieve anything beyond that.  We support 70+ AWS accounts and have at least a handful of users per each account who needs access to Ice.  We have offices on both coasts.  Beyond that, the rest of (my immediate team's) our stack is configured in a similar manner and is the default way we attempt to deploy and support anything.  That doesn't make it "right" for this scenario obviously, just explaining my motives.

Given your feedback that running more than one could lead to inconsistencies, I'll be revisiting how we've structure our deployment.  I will pair down the # of servers in each region to one, and then provide a different s3 bucket for each region.

Thank your for your help and feedback.

**Comment by nfonrose** [comment]
Hi Chris,

Don't you think that to achieve most of what you're trying to achieve
(latency and high availability), you could run redundant Readers but a
single Processor ?

And I'm fairly confident that running several Readers against the same
working bucket wouldn't be an issue.

Nicolas

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
http://www.teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by ckelner** [comment]
Hey @nfonrose that is fine solution as well.  I chose the path of multiple buckets since it will be mostly configuration changes versus architecture changes (which means touching puppet, our CI, etc).  I originally suggested exactly what you suggest to my architect and sys admins, but I was countered with the multiple bucket option and for us it does mean less work.  A single processor in some sort of self-healing (autoscaling), hot:cold (in the event of AZ/region failure) setup would work just fine.
