### ISSUE TITLE
Empty dashboard

### ISSUE THREAD

**Issue by nagashreeck** [Netflix/ice#150]
![captureice](https://cloud.githubusercontent.com/assets/10279880/6265187/52d67daa-b851-11e4-8193-57fc41adf470.PNG)
after installing ice i can able to see in terminal server is running,browse http://localhost:8080/ice
but in browser i am unable to see details.

here is ice.properties

ice.processor=true
ice.reader=true
ice.reservationCapacityPoller=false
ice.reservationPeriod=threeyear
ice.reservationUtilization=MEDIUM
ice.highstockUrl=http://code.highcharts.com/stock/highstock.js
ice.urlPrefix=
ice.fromEmail=
ice.ondemandCostAlertThreshold=250
ice.ondemandCostAlertEmails=
ice.billing_s3bucketname=netflixice
ice.billing_s3bucketprefix=ice/
ice.billing_payerAccountId=,123456789013
ice.billing_accessRoleName=,ice
ice.startmillis=1364774400000
ice.companyName=Bworks
ice.work_s3bucketname=netflixice
ice.work_s3bucketprefix=ice/
ice.processor.localDir=/mnt/ice_processor
ice.reader.localDir=/mnt/ice_reader
ice.monthlycachesize=12

here is my s3 bucket files

![captures3](https://cloud.githubusercontent.com/assets/10279880/6265616/4c7bc2f8-b856-11e4-87b4-a42f1b7dea93.JPG)

**Comment by garlandkr** [comment]
You have ice.billing_s3bucketprefix=ice/ and ice.work_s3bucketprefix=ice/ set which means there should be a subfolder called "ice" in your s3 bucket. If you have the billing files in the root path of the s3 bucket make those lines in ice.properties look like this instead:

```
ice.billing_s3bucketprefix=
ice.work_s3bucketprefix=
```

**Comment by nagashreeck** [comment]
@garlandkr   Thanks for reply.

now i can able to see some files inside s3 bucket as well as ice_processor but i can't able to access in browser again empty dashboard and ice_reader folder is empty.

here is s3 bucket files
![captureice1](https://cloud.githubusercontent.com/assets/10279880/6287284/61cdd340-b936-11e4-848d-fb8e63e44d22.JPG)

**Comment by nagashreeck** [comment]
reopened

**Comment by nagashreeck** [comment]
reopen

**Comment by garlandkr** [comment]
Check your browser console to see if there are any errors.
