### ISSUE TITLE
IllegalArgumentException occurred when processing request: [POST] /ice/dashboard/getData

### ISSUE THREAD

**Issue by nbasu02** [Netflix/ice#212]
I'm not sure how to reproduce this, but it seems that after having left my Netflix ice instance going for some time, some data coming in from AWS isn't complete and it's breaking the entire application.  Here's the whole stacktrace:

```
| Error 2016-05-09 20:47:32,678 [http-nio-8080-exec-2] ERROR errors.GrailsExceptionResolver  - IllegalArgumentException occurred when processing request: [POST] /ice/dashboard/getData
Invalid format: "". Stacktrace follows:
Message: Invalid format: ""
    Line | Method
->>  945 | parseDateTime in org.joda.time.format.DateTimeFormatter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    407 | doGetData     in com.netflix.ice.DashboardController
|    321 | doCall . . .  in com.netflix.ice.DashboardController$_closure11
|   1145 | runWorker     in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run           in java.lang.Thread

```

Anyone have any insight?

**Comment by hatmatter** [comment]
I'm seeing this as well. I just did a fresh install, started the processor/reader on the same instance, waited for it to do it's initial processing. Upon trying to browse the /ice endpoint I see this error as well and data doesn't seem to load into the dashboard. The initial data is populated, accounts, regions, etc, but the dynamic data doesn't appear to be loading.

**Comment by hatmatter** [comment]
This looks like a duplicate of https://github.com/Netflix/ice/issues/210 ?

**Comment by hatmatter** [comment]
@nbasu02 I confirmed that the fix in https://github.com/Netflix/ice/issues/210 to pin the version of highchart to 4.2.4 fixes the issue.

**Comment by nbasu02** [comment]
Perfect, thanks!
