### ISSUE TITLE
Any plan migrate from Detailed Billing Reports to Cost and Usage Reports? 

### ISSUE THREAD

**Issue by bay1188** [Netflix/ice#302]
Any plan migrate from Detailed Billing Reports to Cost and Usage Reports? 
or ICE project is pretty much stopped developing ?

**Comment by nfonrose** [comment]
There is a very active fork of the project that does that (processing CUR reports) and a lot more. It's located here : https://github.com/jimroth/ice

**Comment by bay1188** [comment]
Thanks, I didn't see the instruction in that repo on how to enable CUR report. Does it take CUR format automatically ?

**Comment by nfonrose** [comment]
Yes, it's the default input format
