### ISSUE TITLE
Bug when ice-reader loads the data

### ISSUE THREAD

**Issue by jinhyung** [Netflix/ice#46]
```
| Error 2013-08-14 15:22:56,025 [http-bio-8080-exec-10] ERROR errors.GrailsExceptionResolver  - IllegalArgumentException occurred when processing request: [POST] /ice/dashboard/getData
Invalid format: "2013-08-14 03PM" is malformed at "PM". Stacktrace follows:
Message: Invalid format: "2013-08-14 03PM" is malformed at "PM"
    Line | Method
->>  866 | parseDateTime in org.joda.time.format.DateTimeFormatter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    402 | doGetData     in com.netflix.ice.DashboardController
|    316 | doCall . . .  in com.netflix.ice.DashboardController$_closure11
|   1146 | runWorker     in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    679 | run           in java.lang.Thread
```

After processing data from ice-processor and trying to use ice-reader, I got those errors from ice-reader.

**Comment by liuzongqing** [comment]
@fangji , I also get this error message when i open the dashboard. Can you help me?

The below is my log detail:

| Error 2015-03-23 02:36:26,253 [http-bio-9090-exec-1] ERROR errors.GrailsExceptionResolver  - IllegalArgumentException occurred when processing request: [POST] /ice/dashboard/getData
Invalid format: "2015-03-23 02AM" is malformed at "AM". Stacktrace follows:
Message: Invalid format: "2015-03-23 02AM" is malformed at "AM"
    Line | Method
->>  899 | parseDateTime in org.joda.time.format.DateTimeFormatter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    407 | doGetData     in com.netflix.ice.DashboardController
|    321 | doCall . . .  in com.netflix.ice.DashboardController$_closure11
|   1145 | runWorker     in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run           in java.lang.Thread
1427078186661

**Comment by thinhduckhoi** [comment]
Did anyone solve this problem? I got the same error and couldn't figure out what was the reason.

**Comment by NitriKx** [comment]
What is the TimeZone/Locale of the machine which runs Ice? 
You may have encountered the following problem: http://stackoverflow.com/questions/32045626/joda-hhmm-am-is-malformed-at-am
