### ISSUE TITLE
ice.customTags has no effect

### ISSUE THREAD

**Issue by jlintz** [Netflix/ice#50]
In our account we have a "billing" tag on most of our resources.  I've pulled the latest copy of Ice and added "ice.customTags=billing" to ice.properties but I don't see any references to the tags in the interface anywhere.  We're enabled for the beta detailed billing as well.

**Comment by budaykiran94** [comment]
Hi,

I have specified user:Environment in ice.customTags and also have enabled everything that is required and also I can see the tags in csv file, but I am not able to see the tags in the browser. Is there anything else that I need to do to display the tags in the browser. I have been stuck here for a while. Can anyone here please help me regarding this issue.

Thanks,
Uday

**Comment by hoanglc** [comment]
@budaykiran94 after update the custom tag, you should delete all the file in ice_reader folder and it will calculate again with the new tag.
